name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64

      - name: Build
        run: |
          pipx run nox -s build -- 3.10

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/dist
          if-no-files-found: error
